### ISSUE TITLE
FormatMessage failed to format error

### ISSUE THREAD

**Issue by Sammers21** [rodrigocfd/winsafe-examples#4]
So i'm trying to use video playble example to play the following video downloaded from YouTube: https://www.youtube.com/watch?v=1Uj1b7NZeaY&list=PPSV

Here is the error i get when i'm opening the file: 
![image](https://github.com/rodrigocfd/winsafe-examples/assets/16746106/a7968c13-4f41-4636-b491-de18aaf7ad4d)

I did use https://en.savefrom.net/1-youtube-video-downloader-544tK/ to download that video from youtube. Attaching that video to this ticket: 

https://github.com/rodrigocfd/winsafe-examples/assets/16746106/70e32606-b090-4955-b7cc-fb2377a7b64e

**Comment by Sammers21** [comment]
@rodrigocfd pls take a look

**Comment by rodrigocfd** [comment]
This mp4 file plays fine on my computer.

The playback application uses DirectShow directly, which will use the installed codecs on your machine – that's why the final binary is so lightweight. The problem, of course, is that you must have the proper codecs installed, and you probably don't: `FormatMessage` doesn't even know what [the error](https://support.microsoft.com/en-gb/topic/-cannot-play-back-the-file-the-format-is-not-supported-error-80040265-error-message-when-you-try-to-play-a-media-file-in-windows-media-player-8db7e415-7374-b542-56ab-ed311dc48513) means:

> Cannot play back the file. The format is not supported.

The simplest solution is simply install the proper codecs. If you're unsure, [K-Lite Codec Pack](https://codecguide.com/download_k-lite_codec_pack_mega.htm) will have your back (that's what I have installed).
